### ISSUE TITLE
ABCDEE+Sylfaen are not implemented in PDFBox

### ISSUE THREAD

**Issue by ufo911** [chezou/tabula-py#89] opened 2018-05-02 09:46 UTC
------

# Summary of your issue

# Environment

Write and check your environment. Please paste outputs of specific commands if required.

- [ ] Paste the output of `python --version` command on your terminal: Python 3.6.1
- [ ] Paste the output of `java -version` command on your terminal:  javac 1.8.0_121
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`  yes
- [ ] Write your OS and it's version:  Windows 10
- [ ] (Optional, but really helpful) Your PDF URL: 
[Doc1.pdf](https://github.com/chezou/tabula-py/files/1966735/Doc1.pdf)

# What did you do when you faced the problem?

Tried Many things..

## Example code:

```
PDFfilename2 = "C:\\Users\\LenovoPC\\Desktop\\Doc1.pdf"

df = tabula.read_pdf(PDFfilename2,
             output_format='dataframe',
             encoding='Ansi',
             java_options=None,
             pandas_options=None,
             multiple_tables=False)



df.to_csv('df_output.csv', encoding='utf-8')

print(df)

tabula.convert_into(PDFfilename1,  "output.csv", output_format="csv", )


df.to_csv('otuput.csv', encoding='utf-8')
```

## Output:

```
   sare  ????
0  ????  ????
1  ????  ????
2  ????  ????
3  ????  ????
May 02, 2018 1:34:54 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFO: OpenType Layout tables used in font ABCDEE+Sylfaen are not implemented in PDFBox and will be ignored
May 02, 2018 1:34:54 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFO: OpenType Layout tables used in font ABCDEE+Sylfaen are not implemented in PDFBox and will be ignored
May 02, 2018 1:34:55 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFO: OpenType Layout tables used in font ABCDEE+Sylfaen are not implemented in PDFBox and will be ignored


```

## What did you intend to be?

   sare  რამე
0  რამე  რამე
1  რამე  რამე
3 რამე  რამე
3 რამე  რამე

IN Addition !
code does work for ENG symbols.

**Comment by chezou** [comment] 2018-05-02 13:48
If tabula-java works fine with appropriate encoding, it could work with setting `encoding` option for `read_pdf` function. But I can't check with your language because my environment is Japanese one.

Could you check the result of the following command? Please replace appropriate place for jar file.

```
java -jar .\tabula\tabula-1.0.1-jar-with-dependencies.jar .\Doc1.pdf
```

If it works fine, it might be tabula-py's option issue, setting `Ansti` could ignore all the UTF-8 related encoding. If it doesn't work, it might be tabula-java issue or just terminal setting issue. In that case, I can't help anything. See also: https://github.com/tabulapdf/tabula-java/issues/204

**Comment by ufo911** [comment] 2018-05-02 14:55
The result is same with the command, and it is Tabula Java issue and they have updated version and can you also update .jar ?

https://github.com/chezou/tabula-py/issues/31

**Comment by chezou** [comment] 2018-05-02 21:46
I don't understand why you refer https://github.com/chezou/tabula-py/issues/31 I think this issue had been solved with tabula-py v1.0.0.
If you state it is tabula-java issue, could you raise anissue on tabula-java repo? tabula-py uses latest released version of tabula-java and I don't want to release with master commit of it.

**Comment by chezou** [comment] 2018-05-02 21:52
I'll close this issue because of it is not tabula-py issue. Feel free to create an issue to bump up tabula-py after latest tabula-java will be released.

**Closed by chezou** 2018-05-02 21:52 UTC

**Comment by ufo911** [comment] 2018-05-03 05:39
It is embedded fonts issue with tabula java and I don't know if they are going to fixt that and can you help me ?  your tool is only one which can parse tables and please report my issue to tabula java or help me to get them report the issue. thanks

**Comment by chezou** [comment] 2018-05-03 05:52
First of all, it's out of scope of tabula-py since tabula-java couldn't output appropriately at least my Japanese Windows environment. Secondly, I can't reproduce embedded font **INFO** message and the message shows the issue of PDF and it is always said the problem of PDF itself. If you think this is tabula-java issue, please create an issue on tabula-java. I'm willing to update if tabula-java releases new version which can avoid this problem.

Here is my two cents, I can confirm tabula-java and tabula-py works fine for this PDF with Ubuntu on Windows Subsystem Linux.

Anyway, I'm sorry to say that I can't do anymore because it's not tabula-py problem.

**Comment by ufo911** [comment] 2018-05-04 09:26
https://issues.apache.org/jira/plugins/servlet/mobile#issue/PDFBOX-4208

I also reported to pdfbox and they are telling that it is working in pdf box 2.0.9
I also reported tabula java

**Comment by ufo911** [comment] 2018-05-06 06:15
https://github.com/tabulapdf/tabula-java/issues/221

maybe tabula py has bug they are extraxting text

**Comment by chezou** [comment] 2018-05-06 07:00
No. tabula-py can extract text with Ubuntu 18.04. It could be a terminal setting issue on your Windows.

````
$ ipython
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tabula

In [2]: df = tabula.read_pdf("Doc1.pdf")

In [3]: df
Out[3]: 
   sare  რამე
0  რამე  რამე
1  რამე  რამე
2  რამე  რამე
3  რამე  რამე
```

**Comment by ufo911** [comment] 2018-05-06 08:30
Please try to convert to CSV and tell me result... upload file here
Thanks

**Comment by chezou** [comment] 2018-05-06 08:51
Here is converted files using the following script: [doc1_converted.zip](https://github.com/chezou/tabula-py/files/1977468/doc1_converted.zip)
143d88-5155-11e8-8a92-936434aec445.png)


```
 tabula-test ipython
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tabula

In [2]: tabula.convert_into("Doc1.pdf", "doc1_converted.csv")

In [3]: !ls
Doc1.pdf  doc1_converted.csv  venv

In [4]: !cat doc1_converted.csv
sare,რამე
"რამე",რამე
"რამე",რამე
"რამე",რამე
"რამე",რამე

In [5]: df = tabula.read_pdf("Doc1.pdf")

In [6]: df.to_csv("doc1_via_pandas.csv")

In [7]: !cat doc1_via_pandas.csv
,sare,რამე
0,რამე,რამე
1,რამე,რამე
2,რამე,რამე
3,რამე,რამე
```

I will provide the screenshot of this code.

![screenshot from 2018-05-06 17-43-20](https://user-images.githubusercontent.com/916653/39671593-16fec0d4-5156-11e8-9d6a-c0a8406c8499.png)


Just FYI, I also confirmed it works fine with [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10), which enables you to install Ubuntu on Windows 10.
