### ISSUE TITLE
Extract hyperlinks from tables

### ISSUE THREAD

**Issue by KayleMaster** [chezou/tabula-py#236] opened 2020-04-21 13:44 UTC
**Is your feature request related to a problem? Please describe.**

I have a PDF with tables that contains hyperlinks (embedded, not in plain text). Tabula extracts the text fine, but the URL is gone.    

**Describe the solution you'd like**

An option that exports hyperlinks as plaintext, maybe in square brackets after the text.   

**Describe alternatives you've considered**

Py2PDF, very heavy and very hard to work with compared to tabula.

**Comment by chezou** [comment] 2020-06-04 08:39
@KayleMaster Could you give me an example PDF? I'm wondering whether tabula-java, on which tabula-py depends, extracts the hyperlinks.

**Comment by KayleMaster** [comment] 2020-06-15 12:44
@chezou There you go.  
[EkstraktHistorik-5_20_2020.pdf](https://github.com/chezou/tabula-py/files/4780265/EkstraktHistorik-5_20_2020.pdf)  
I've written a custom solution to extract links from PDF's but it's completely separate from tabula, so I can't know which link to which cell belongs. I use camelot for my table extraction for various reasons, but seeing as you're based on tabula-java that'd mean you'd have to contribute to that in order to get hyperlink extraction working.

**Comment by chezou** [comment] 2020-07-01 04:34
@KayleMaster Thanks for the PDF. I confirmed tabula-java doesn't help to extract, nor tabula-py. Currently, I think this is a matter of tabula-java layer and have no idea how the output should be.

Do you have any specific thought to handle tabula-py layer?

**Comment by KayleMaster** [comment] 2020-07-02 19:14
It might be possible on this layer as well.   
If you're wrapping around a high-level tabula-java API it might not work.  
All you need is the absolute (PDF) coordinates of text in a cell. If you have those you can crosscheck the Annotations from the metadata and post process the text to add links to them (using square brackets or whatever).

**Comment by chezou** [comment] 2020-07-03 11:58
I don't think it's tabula-py's responsibility at this moment. I'm going to close this issue since I think it'd be better to create a ticket on tabula-java.

However, tabula-py is open-source software, if you have an idea to solve it, I'd be happy to see a pull request for this feature.

**Closed by chezou** 2020-07-03 11:58 UTC
Labels: enhancement, tabula-java limitation
