### ISSUE TITLE
I can't run on python 3.13

### ISSUE THREAD

**Issue by staciax** [chezou/tabula-py#401] opened 2024-10-16 08:27 UTC
### Summary

i can't use tabula on python 3.13 but it's work on 3.12.7

### Did you read the FAQ?

- [X] I have read the FAQ

### Did you search GitHub issues?

- [X] I have searched the issues

### Did you search GitHub Discussions?

- [X] I have searched the discussions

### About your environment

```markdown
Python version:
    3.13.0 (v3.13.0:60403a5409f, Oct  7 2024, 00:37:40) [Clang 15.0.0 (clang-1500.3.9.4)]
Java version:
    openjdk version "23" 2024-09-17
OpenJDK Runtime Environment Homebrew (build 23)
OpenJDK 64-Bit Server VM Homebrew (build 23, mixed mode, sharing)
tabula-py version: 2.9.3
platform: macOS-15.0.1-arm64-arm-64bit-Mach-O
uname:
    uname_result(system='Darwin', node='STACIAs-MacBook-Air.local', release='24.0.0', version='Darwin Kernel Version 24.0.0: Tue Sep 24 23:38:45 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8122', machine='arm64')
linux_distribution: ('Darwin', '24.0.0', '')
mac_ver: ('15.0.1', ('', '', ''), 'arm64')
```

### What did you do when you faced the problem?

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001012703d8, pid=79931, tid=259
#
# JRE version: OpenJDK Runtime Environment Homebrew (23.0) (build 23)
# Java VM: OpenJDK 64-Bit Server VM Homebrew (23, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [Python+0x28c3d8]  _PyObject_GC_New+0x148
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/stacia/Documents/GitHub/waku-waku/hs_err_pid79931.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/Homebrew/homebrew-core/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

after run `ulimit -c unlimited`

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000104fc03d8, pid=80701, tid=259
#
# JRE version: OpenJDK Runtime Environment Homebrew (23.0) (build 23)
# Java VM: OpenJDK 64-Bit Server VM Homebrew (23, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [Python+0x28c3d8]  _PyObject_GC_New+0x148
#
# Core dump will be written. Default location: /cores/core.80701
#
# An error report file with more information is saved as:
# /Users/stacia/Documents/GitHub/waku-waku/hs_err_pid80701.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/Homebrew/homebrew-core/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

### Code

```py
import tabula

tabula.convert_into_by_batch(
    input_dir='pdf',
    output_format='csv',
    pages='all',
)
```

### Expected behavior

convert csv to pdf

### Actual behavior

error but it work on python 3.12.7

**Comment by chezou** [comment] 2024-10-16 22:37
Thanks for reporting. I can reproduce the issue on CI. https://github.com/chezou/tabula-py/actions/runs/11374683206/job/31643896982

It seems jpype doesn't support Python 3.13 yet. That's the cause. Meanwhile, can you try to remove jpype, or pass `force_subprocess=True` option?
https://github.com/jpype-project/jpype/issues/1204

**Comment by staciax** [comment] 2024-10-18 10:52
> Thanks for reporting. I can reproduce the issue on CI. https://github.com/chezou/tabula-py/actions/runs/11374683206/job/31643896982
> 
> It seems jpype doesn't support Python 3.13 yet. That's the cause. Meanwhile, can you try to remove jpype, or pass `force_subprocess=True` option? [jpype-project/jpype#1204](https://github.com/jpype-project/jpype/issues/1204)

sorry for late reply 

i'm tryna pass `force_subprocess=True` its' working now ❤️ 

```
Python version:
    3.13.0 (v3.13.0:60403a5409f, Oct  7 2024, 00:37:40) [Clang 15.0.0 (clang-1500.3.9.4)]
Java version:
    openjdk version "23" 2024-09-17
OpenJDK Runtime Environment Homebrew (build 23)
OpenJDK 64-Bit Server VM Homebrew (build 23, mixed mode, sharing)
tabula-py version: 2.9.3
platform: macOS-15.0.1-arm64-arm-64bit-Mach-O
uname:
    uname_result(system='Darwin', node='STACIAs-MacBook-Air.local', release='24.0.0', version='Darwin Kernel Version 24.0.0: Tue Sep 24 23:38:45 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8122', machine='arm64')
linux_distribution: ('Darwin', '24.0.0', '')
mac_ver: ('15.0.1', ('', '', ''), 'arm64')
```

**Comment by staciax** [comment] 2024-10-18 10:57
i'm try again at 2.10.0 it's working too with pass `force_subprocess=True`

**Comment by chezou** [comment] 2024-10-18 14:39
Thank you for your confirmation. Let me close this issue and will keep eyes open for jpype situation.

**Closed** 2024-10-18 14:40 UTC
Labels: jpype issue
